feature/Add-Encrypted-Preferences-and-Retrofit-Interceptor
jhostinLuna/ChiChat pull request #15
Opened 2024-06-21 11:23 UTC by jhostinLuna

2024-06-21 11:38 UTC, AntonioJesusRM commented on app/src/main/java/com/team2/chitchat/data/repository/remote/request/users/LoginUserRequest.kt
este cambio no le veo sentido según entendí la request no hace falta serializarla por el nombre dado que ya pones el mismo nombre que pide los parámetros del servidor

2024-06-21 11:40 UTC, AntonioJesusRM commented on app/src/main/java/com/team2/chitchat/ui/extensions/Extensions.kt
El archivo de extension esta en la carpeta utils

2024-06-21 11:45 UTC, AntonioJesusRM reviewed
Mira los comentarios, a ver que te parecen

2024-06-21 15:33 UTC, jhostinLuna commented on app/src/main/java/com/team2/chitchat/data/repository/remote/request/users/LoginUserRequest.kt
Es cierto Antonio no hace falta y creo que tampoco estorba, la puse para resolver un error cuando pensaba que era el motivo.

2024-06-21 15:35 UTC, jhostinLuna commented on app/src/main/java/com/team2/chitchat/ui/extensions/Extensions.kt
la ruta la he copiado de el ejemplo de BaseProject, pendiente de modificarla....

2024-06-21 16:11 UTC, AntonioJesusRM approved these changes

2024-06-21 18:16 UTC, sebasgpachano commented on app/src/main/java/com/team2/chitchat/ui/login/LoginFragment.kt
> +                        Toast.makeText(context,"Por favor ingresa usuario y contraseña válidos",Toast.LENGTH_LONG)
Aquí tenemos que colorear el editText de rojo y poner el mensaje de error

2024-06-21 18:19 UTC, sebasgpachano requested changes
Falta poner el error de los editText como en figma

2024-06-21 18:28 UTC, sebasgpachano commented on app/src/main/java/com/team2/chitchat/ui/login/LoginFragment.kt
> +
Aquí necesitas manejar los errores de si el usuario no existe o la contraseña está mal, para marcar los editText en rojo

2024-06-21 18:30 UTC, sebasgpachano commented on app/src/main/java/com/team2/chitchat/ui/login/LoginFragment.kt
> +                        Toast.makeText(context,"Por favor ingresa usuario y contraseña válidos",Toast.LENGTH_LONG)
Ya hay un método en extensions para el toast

2024-06-22 14:32 UTC, sebasgpachano approved these changes

2024-06-22 14:33 UTC, merged